# Linear Interpolation of time series data
The code from git hub can be used to import the necessary objects and functions to impute the data. This sheet will help explain how.

In [3]:
from tsl_imputer import (
    linear_interpolation,
    get_file,
    Imputer)
import pandas as pd
import numpy as np

### Imputing the data - step by step
In the following code, we take you through the process so you can see what the data looked like before and after.<br><br>
Select the csv file "test_all_groups.csv" to get the results talked about in the explanation below.

In [4]:
admin_cols = 2
filename = get_file()
df = pd.read_csv(filename)
imp = Imputer(df,admin_cols)
imp.data

,Subject,Row,0,15,30,60,90,120,240
0,129501,0,320.5,260.0,235.0,208.0,198.0,208.0,208.0
1,129502,1,328.5,338.0,240.0,240.0,225.0,280.0,275.0
2,129503,2,265.5,297.0,353.5,410.0,291.0,262.0,NaN
3,129504,3,NaN,NaN,167.0,469.0,501.0,461.0,455.0
4,129505,4,321.0,345.5,370.0,479.0,253.0,223.0,243.0
5,129506,5,660.0,587.0,NaN,568.0,345.0,213.0,NaN
6,129507,6,584.5,617.0,521.0,474.0,463.0,531.0,526.0
7,129508,7,415.0,NaN,NaN,NaN,288.0,371.0,445.0
8,129510,8,622.5,592.0,628.0,664.0,664.0,686.0,764.0
9,129511,9,NaN,764.0,739.0,NaN,727.0,779.0,929.0


As you can see with the test file, there are several rows of data (10 to be exact) that are missing data. The constructor method for the Imputer actually creates two data structures with the rows and columns. Let's check them out:

In [5]:
imp.rows

array([ 2,  3,  5,  7,  9, 10, 14, 18, 19, 20], dtype=int64)

This means that there is data missing in rows 2,3,5,7,... and so on. You can verify that by looking at the printed out data frame.<br><br>
Now lets see the columns that are missing data for each of the listed rows...

In [6]:
imp.cols

[array([6], dtype=int64),
 array([0, 1], dtype=int64),
 array([2, 6], dtype=int64),
 array([1, 2, 3], dtype=int64),
 array([0, 3], dtype=int64),
 array([4], dtype=int64),
 array([3, 4], dtype=int64),
 array([0], dtype=int64),
 array([1, 4], dtype=int64),
 array([5, 6], dtype=int64)]

This means that row 2 has missing data in column 6, row 3 has data missing in columns 0 and 1, row 5 has data missing in columns 2 and 6, and so on.

We now are set to impute data or throw out a row if it does not meet the criteria. Nothing has been done yet.

In [7]:
imp.imputed_data

[]

In [8]:
imp.impute_data()

,Subject,Row,0,15,30,60,90,120,240
0,129501,0,320.5,260.0,235.0,208.0,198.0,208.0,208.0
1,129502,1,328.5,338.0,240.0,240.0,225.0,280.0,275.0
2,129503,2,265.5,297.0,353.5,410.0,291.0,262.0,146.0
4,129505,4,321.0,345.5,370.0,479.0,253.0,223.0,243.0
6,129507,6,584.5,617.0,521.0,474.0,463.0,531.0,526.0
8,129510,8,622.5,592.0,628.0,664.0,664.0,686.0,764.0
9,129511,9,789.0,764.0,739.0,733.0,727.0,779.0,929.0
10,129512,10,707.5,450.0,548.0,578.0,711.0,844.0,844.0
11,129515,11,805.0,704.0,582.0,582.0,636.0,582.0,800.0
12,129516,12,309.5,335.0,307.0,284.0,314.0,177.0,217.0


Once the method `impute_data` is run, the output is the new data frame with the rows that passed the conditions of being imputed (less than 3 missing data and no negative values).

In [9]:
# Note that this is not the method, this data frame is stored in the imp object and can be used later.
imp.imputed_data

,Subject,Row,0,15,30,60,90,120,240
0,129501,0,320.5,260.0,235.0,208.0,198.0,208.0,208.0
1,129502,1,328.5,338.0,240.0,240.0,225.0,280.0,275.0
2,129503,2,265.5,297.0,353.5,410.0,291.0,262.0,146.0
4,129505,4,321.0,345.5,370.0,479.0,253.0,223.0,243.0
6,129507,6,584.5,617.0,521.0,474.0,463.0,531.0,526.0
8,129510,8,622.5,592.0,628.0,664.0,664.0,686.0,764.0
9,129511,9,789.0,764.0,739.0,733.0,727.0,779.0,929.0
10,129512,10,707.5,450.0,548.0,578.0,711.0,844.0,844.0
11,129515,11,805.0,704.0,582.0,582.0,636.0,582.0,800.0
12,129516,12,309.5,335.0,307.0,284.0,314.0,177.0,217.0


In [10]:
imp.deleted_rows

[7, 5, 3]

Note that rows 3,5, and 7 were deleted by the algorithm because one of the conditions were not met.

As an alternative, one can simply run the linear_interpolation function and it will do all of these steps for you.

In [12]:
admin_cols = 2
new_data = linear_interpolation(admin_cols)
new_data

,Subject,Row,0,15,30,60,90,120,240
0,129501,0,320.5,260.0,235.0,208.0,198.0,208.0,208.0
1,129502,1,328.5,338.0,240.0,240.0,225.0,280.0,275.0
2,129503,2,265.5,297.0,353.5,410.0,291.0,262.0,146.0
4,129505,4,321.0,345.5,370.0,479.0,253.0,223.0,243.0
6,129507,6,584.5,617.0,521.0,474.0,463.0,531.0,526.0
8,129510,8,622.5,592.0,628.0,664.0,664.0,686.0,764.0
9,129511,9,789.0,764.0,739.0,733.0,727.0,779.0,929.0
10,129512,10,707.5,450.0,548.0,578.0,711.0,844.0,844.0
11,129515,11,805.0,704.0,582.0,582.0,636.0,582.0,800.0
12,129516,12,309.5,335.0,307.0,284.0,314.0,177.0,217.0
